const data = `
be	was,were	been	être
become	became	become	devenir
begin	began	begun	commencer
bend	bent	bent	courber
bet	bet	bet	parier
bite	bit	bitten	mordre
bleed	bled	bled	saigner
blow	blew	blown	souffler
break	broke	broken	casser
bring	brought	brought	apporter
build	built	built	construire
burn	burnt	burnt	brûler
burst	burst	burst	éclater
buy	bought	bought	acheter
cast	cast	cast	lancer
catch	caught	caught	attraper
choose	chose	chosen	choisir
come	came	come	venir
cost	cost	cost	coûter
cut	cut	cut	couper
deal	dealt	dealt	distribuer
do	did	done	faire
draw	drew	drawn	dessiner
dream	dreamt	dreamt	rêver
drink	drank	drunk	boire
drive	drove	driven	conduire
eat	ate	eaten	manger
fall	fell	fallen	tomber
feed	fed	fed	nourrir
feel	felt	felt	sentir
fight	fought	fought	combattre
find	found	found	trouver
fly	flew	flown	voler
forbid	forbade	forbidden	interdire
forget	forgot	forgotten	oublier
forgive	forgave	forgiven	pardonner
freeze	froze	frozen	geler
get	got	got	obtenir
give	gave	given	donner
go	went	gone	aller
grow	grew	grown	pousser(croître)
have	had	had	avoir
hear	heard	heard	entendre
hide	hid	hidden	cacher
hit	hit	hit	frapper
hold	held	held	tenir
hang	hung	hung	pendre/suspendre
hurt	hurt	hurt	blesser
keep	kept	kept	garder
know	knew	known	connaître
lay	laid	laid	poser à plat
lead	led	led	mener
leap	leapt	leapt	sauter
learn	learnt	learnt	apprendre
leave	left	left	quitter
lend	lent	lent	préter
let	let	let	laisser
lie	lay	lain	être couché
light	lit	lit	allumer
lose	lost	lost	perdre
make	made	made	faire(fabriquer)
mean	meant	meant	signifier
meet	met	met	rencontrer
pay	paid	paid	payer
put	put	put	mettre
read	read	read	lire
ride	rode	ridden	aller à cheval
ring	rang	rung	sonner
rise	rose	risen	s'élever
run	ran	run	courir
sit	sat	sat	être assis
say	said	said	dire
see	saw	seen	voir
sell	sold	sold	vendre
send	sent	sent	envoyer
set	set	set	placer
shake	shook	shaken	secouer
shoot	shot	shot	tirer/faire feu
show	showed	shown	montrer
shut	shut	shut	fermer
sing	sang	sung	chanter
sink	sank	sunk	couler
sleep	slept	slept	dormir
slide	slid	slid	glisser
smell	smelt	smelt	sentir
speak	spoke	spoken	parler
spell	spelt	spelt	épeler
spend	spent	spent	dépenser
spill	spilt	spilt	répandre
split	split	split	fendre
spoil	spoilt	spoilt	gâter(gâcher)
spread	spread	spread	répandre/étaler
stand	stood	stood	être debout
steal	stole	stolen	voler(qqch)
stick	stuck	stuck	coller
strike	struck	struck	frapper
swear	swore	sworn	jurer
sweep	swept	swept	balayer
swim	swam	swum	nager
swing	swung	swung	(se)balancer
take	took	taken	prendre
teach	taught	taught	enseigner
tear	tore	torn	déchirer
tell	told	told	dire
think	thought	thought	penser
throw	threw	thrown	lancer(jeter)
understand	understood	understood	comprendre
wake	woke	woken	réveiller
wear	wore	worn	porter(vêtement)
win	won	won	gagner
write	wrote	written	écrire
`

